dataset_config:
  data_name: "granular"
  materials: ["granular"]
  data_dir: "../sim_data" # data directory
  prep_data_dir: "../preprocess" # preprocessed data directory
  device: "cuda:0"

  verbose: False
  # preprocess
  n_his: 4
  n_future: 3
  dist_thresh: 0.2 # 2.0cm

  ratio:
    train: [0, 0.98]
    valid: [0.98, 1]

  eef:
    max_neef: 5
    name: ['flat_pusher']
    pos: [[0.5, 0.045, 1.25],
          [-0.5, 0.045, 1.25],
          [0., 0.045, 1.25],
          [0.25, 0.045, 1.25],
          [-0.25, 0., 1.25]]
  
  datasets:
    - name: 'granular'
      max_nobj: 100
      max_nR: 1000
      fps_radius_range: [0.18, 0.22]
      adj_radius_range: [0.38, 0.42]
      topk: 20
      connect_tool_all: False
  
  randomness: 
    use: False
    state_noise:
      train: 0.04
      valid: 0.0
    phys_noise:
      train: 0.0
      valid: 0.0
    
train_config:
  out_dir: "../log"
  phases: ['train', 'valid']
  num_workers: 1
  random_seed: 42
  verbose: False

  batch_size: 128
  n_epochs: 100
  n_iters_per_epoch: 
    train: 1000
    valid: 100
  log_interval: 50

model_config:
  verbose: False

  nf_particle: 150
  nf_relation: 150
  nf_effect: 150
  nf_physics: 10

  # particle encoder
  attr_dim: 2 # object and eef
  state_dim: 0 # x, y, z 
  offset_dim: 0
  action_dim: 3
  density_dim: 0 # particle density

  pstep: 3 # propagation steps
  sequence_len: 4
  
  # relation encoder
  rel_particle_dim: 0
  rel_attr_dim: 2 # within objects, object-eef
  rel_group_dim: 1 # sum of difference of group one-hot vector
  rel_distance_dim: 3
  rel_density_dim: 0

rollout_config:
  out_dir: "../rollout"
  rollout_steps: 100

material_config:
  material_index:
    granular: 0
  granular:
    physics_params: 
      - name: "particle_radius"
        use: False
        min: 0.
        max: 1.
      - name: "num_particles"
        use: False
        min: 0.
        max: 5000.
      - name: "granular_scale"
        use: True
        min: 0.1
        max: 0.3
      - name: "num_granular"
        use: False
        min: 9
        max: 645
      - name: "distribution_r"
        use: False
        min: 0.1
        max: 0.3
      - name: "dynamic_friction"
        use: False
        min: 0.2
        max: 0.9
      - name: "granular_mass"
        use: False
        min: 0.01
        max: 0.1