task_config:
  material: cloth
  config: config/dynamics/cloth.yaml
  epoch: 100

  material_indices:
    cloth: 0
  material_dims:
    cloth: 1
  fps_radius: 0.30
  adj_thresh: 0.75  # effect the edge num
  topk: 5  # effect the edge num
  eef_num: 1
  connect_tools_all: True

  sim_real_ratio: 10
  push_length: 0.1
  rotate_pusher: True
  pusher_points:
    - [0.0, 0.0, 0.170]
  bbox: [-0.45, 0.0, -0.25, 0.45, -0.2, 0.05]
  clipping_height: -0.061
  gripper_enable: True

  obj_list: ['cloth']  # include target objects
  k_filter: 1.0

  action_lower_lim: [0.05, 0.007, 0.05, 0.248]  # sim_real_ratio * bbox
  action_upper_lim: [0.296, 0.444, 0.296, 0.688]  # sim_real_ratio * bbox
  max_n: 1
  max_nobj: 200
  max_nR: 5000
  n_his: 4

  target_type: pcd
  target: planning/dump/vis_cloth/cloth_points_40.pcd
  penalty_type: cloth

  n_actions: 10
  n_look_ahead: 1
  n_sample: 200  # Reduced from 20000  # The number of cloth points (down sample if needed)
  n_sample_chunk: 64  # Reduced from 500  # The action batch size
  noise_level: 1.0
  reward_weight: 500.0

  # cloth_resolution: [10, 10]
  # cloth_size: [0.2, 0.2]

  cloth_size: [0.5, 0.5]
  cloth_resolution: [101, 101]